/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AssessmentRouteImport } from './routes/assessment'
import { Route as ExpertsRouteImport } from './routes/experts'
import { Route as ResultsRouteImport } from './routes/results'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as ThailandCallRouteImport } from './routes/thailand-call'
import { Route as ExpertsIndexRouteImport } from './routes/experts.index'
import { Route as ThailandCallIndexRouteImport } from './routes/thailand-call.index'
import { Route as ThailandCallConfirmedRouteImport } from './routes/thailand-call.confirmed'
import { Route as ApiPublicBookingsRouteImport } from './routes/api/public/bookings'
import { Route as ApiPublicLeadsRouteImport } from './routes/api/public/leads'
import { Route as ApiPublicOfferCheckoutRouteImport } from './routes/api/public/offer-checkout'
import { Route as ApiPublicOfferCheckoutConfirmRouteImport } from './routes/api/public/offer-checkout.confirm'
import { Route as LovableEmailAuthPreviewRouteImport } from './routes/lovable/email/auth/preview'
import { Route as LovableEmailAuthWebhookRouteImport } from './routes/lovable/email/auth/webhook'
import { Route as LovableEmailTransactionalPreviewRouteImport } from './routes/lovable/email/transactional/preview'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AssessmentRoute = AssessmentRouteImport.update({
  id: '/assessment',
  path: '/assessment',
  getParentRoute: () => rootRouteImport,
} as any)
const ExpertsRoute = ExpertsRouteImport.update({
  id: '/experts',
  path: '/experts',
  getParentRoute: () => rootRouteImport,
} as any)
const ResultsRoute = ResultsRouteImport.update({
  id: '/results',
  path: '/results',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const ThailandCallRoute = ThailandCallRouteImport.update({
  id: '/thailand-call',
  path: '/thailand-call',
  getParentRoute: () => rootRouteImport,
} as any)
const ExpertsIndexRoute = ExpertsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ExpertsRoute,
} as any)
const ThailandCallIndexRoute = ThailandCallIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ThailandCallRoute,
} as any)
const ThailandCallConfirmedRoute = ThailandCallConfirmedRouteImport.update({
  id: '/confirmed',
  path: '/confirmed',
  getParentRoute: () => ThailandCallRoute,
} as any)
const ApiPublicBookingsRoute = ApiPublicBookingsRouteImport.update({
  id: '/api/public/bookings',
  path: '/api/public/bookings',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicLeadsRoute = ApiPublicLeadsRouteImport.update({
  id: '/api/public/leads',
  path: '/api/public/leads',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicOfferCheckoutRoute = ApiPublicOfferCheckoutRouteImport.update({
  id: '/api/public/offer-checkout',
  path: '/api/public/offer-checkout',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicOfferCheckoutConfirmRoute =
  ApiPublicOfferCheckoutConfirmRouteImport.update({
    id: '/confirm',
    path: '/confirm',
    getParentRoute: () => ApiPublicOfferCheckoutRoute,
  } as any)
const LovableEmailAuthPreviewRoute = LovableEmailAuthPreviewRouteImport.update({
  id: '/lovable/email/auth/preview',
  path: '/lovable/email/auth/preview',
  getParentRoute: () => rootRouteImport,
} as any)
const LovableEmailAuthWebhookRoute = LovableEmailAuthWebhookRouteImport.update({
  id: '/lovable/email/auth/webhook',
  path: '/lovable/email/auth/webhook',
  getParentRoute: () => rootRouteImport,
} as any)
const LovableEmailTransactionalPreviewRoute =
  LovableEmailTransactionalPreviewRouteImport.update({
    id: '/lovable/email/transactional/preview',
    path: '/lovable/email/transactional/preview',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/assessment': typeof AssessmentRoute
  '/experts': typeof ExpertsRouteWithChildren
  '/results': typeof ResultsRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/thailand-call': typeof ThailandCallRouteWithChildren
  '/thailand-call/confirmed': typeof ThailandCallConfirmedRoute
  '/experts/': typeof ExpertsIndexRoute
  '/thailand-call/': typeof ThailandCallIndexRoute
  '/api/public/bookings': typeof ApiPublicBookingsRoute
  '/api/public/leads': typeof ApiPublicLeadsRoute
  '/api/public/offer-checkout': typeof ApiPublicOfferCheckoutRouteWithChildren
  '/api/public/offer-checkout/confirm': typeof ApiPublicOfferCheckoutConfirmRoute
  '/lovable/email/auth/preview': typeof LovableEmailAuthPreviewRoute
  '/lovable/email/auth/webhook': typeof LovableEmailAuthWebhookRoute
  '/lovable/email/transactional/preview': typeof LovableEmailTransactionalPreviewRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/assessment': typeof AssessmentRoute
  '/results': typeof ResultsRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/thailand-call/confirmed': typeof ThailandCallConfirmedRoute
  '/experts': typeof ExpertsIndexRoute
  '/thailand-call': typeof ThailandCallIndexRoute
  '/api/public/bookings': typeof ApiPublicBookingsRoute
  '/api/public/leads': typeof ApiPublicLeadsRoute
  '/api/public/offer-checkout': typeof ApiPublicOfferCheckoutRouteWithChildren
  '/api/public/offer-checkout/confirm': typeof ApiPublicOfferCheckoutConfirmRoute
  '/lovable/email/auth/preview': typeof LovableEmailAuthPreviewRoute
  '/lovable/email/auth/webhook': typeof LovableEmailAuthWebhookRoute
  '/lovable/email/transactional/preview': typeof LovableEmailTransactionalPreviewRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/assessment': typeof AssessmentRoute
  '/experts': typeof ExpertsRouteWithChildren
  '/results': typeof ResultsRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/thailand-call': typeof ThailandCallRouteWithChildren
  '/thailand-call/confirmed': typeof ThailandCallConfirmedRoute
  '/experts/': typeof ExpertsIndexRoute
  '/thailand-call/': typeof ThailandCallIndexRoute
  '/api/public/bookings': typeof ApiPublicBookingsRoute
  '/api/public/leads': typeof ApiPublicLeadsRoute
  '/api/public/offer-checkout': typeof ApiPublicOfferCheckoutRouteWithChildren
  '/api/public/offer-checkout/confirm': typeof ApiPublicOfferCheckoutConfirmRoute
  '/lovable/email/auth/preview': typeof LovableEmailAuthPreviewRoute
  '/lovable/email/auth/webhook': typeof LovableEmailAuthWebhookRoute
  '/lovable/email/transactional/preview': typeof LovableEmailTransactionalPreviewRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/assessment'
    | '/experts'
    | '/results'
    | '/sitemap.xml'
    | '/thailand-call'
    | '/thailand-call/confirmed'
    | '/experts/'
    | '/thailand-call/'
    | '/api/public/bookings'
    | '/api/public/leads'
    | '/api/public/offer-checkout'
    | '/api/public/offer-checkout/confirm'
    | '/lovable/email/auth/preview'
    | '/lovable/email/auth/webhook'
    | '/lovable/email/transactional/preview'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/assessment'
    | '/results'
    | '/sitemap.xml'
    | '/thailand-call/confirmed'
    | '/experts'
    | '/thailand-call'
    | '/api/public/bookings'
    | '/api/public/leads'
    | '/api/public/offer-checkout'
    | '/api/public/offer-checkout/confirm'
    | '/lovable/email/auth/preview'
    | '/lovable/email/auth/webhook'
    | '/lovable/email/transactional/preview'
  id:
    | '__root__'
    | '/'
    | '/assessment'
    | '/experts'
    | '/results'
    | '/sitemap.xml'
    | '/thailand-call'
    | '/thailand-call/confirmed'
    | '/experts/'
    | '/thailand-call/'
    | '/api/public/bookings'
    | '/api/public/leads'
    | '/api/public/offer-checkout'
    | '/api/public/offer-checkout/confirm'
    | '/lovable/email/auth/preview'
    | '/lovable/email/auth/webhook'
    | '/lovable/email/transactional/preview'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AssessmentRoute: typeof AssessmentRoute
  ExpertsRoute: typeof ExpertsRouteWithChildren
  ResultsRoute: typeof ResultsRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  ThailandCallRoute: typeof ThailandCallRouteWithChildren
  ApiPublicBookingsRoute: typeof ApiPublicBookingsRoute
  ApiPublicLeadsRoute: typeof ApiPublicLeadsRoute
  ApiPublicOfferCheckoutRoute: typeof ApiPublicOfferCheckoutRouteWithChildren
  LovableEmailAuthPreviewRoute: typeof LovableEmailAuthPreviewRoute
  LovableEmailAuthWebhookRoute: typeof LovableEmailAuthWebhookRoute
  LovableEmailTransactionalPreviewRoute: typeof LovableEmailTransactionalPreviewRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/assessment': {
      id: '/assessment'
      path: '/assessment'
      fullPath: '/assessment'
      preLoaderRoute: typeof AssessmentRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/experts': {
      id: '/experts'
      path: '/experts'
      fullPath: '/experts'
      preLoaderRoute: typeof ExpertsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/results': {
      id: '/results'
      path: '/results'
      fullPath: '/results'
      preLoaderRoute: typeof ResultsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/thailand-call': {
      id: '/thailand-call'
      path: '/thailand-call'
      fullPath: '/thailand-call'
      preLoaderRoute: typeof ThailandCallRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/experts/': {
      id: '/experts/'
      path: '/'
      fullPath: '/experts/'
      preLoaderRoute: typeof ExpertsIndexRouteImport
      parentRoute: typeof ExpertsRoute
    }
    '/thailand-call/': {
      id: '/thailand-call/'
      path: '/'
      fullPath: '/thailand-call/'
      preLoaderRoute: typeof ThailandCallIndexRouteImport
      parentRoute: typeof ThailandCallRoute
    }
    '/thailand-call/confirmed': {
      id: '/thailand-call/confirmed'
      path: '/confirmed'
      fullPath: '/thailand-call/confirmed'
      preLoaderRoute: typeof ThailandCallConfirmedRouteImport
      parentRoute: typeof ThailandCallRoute
    }
    '/api/public/bookings': {
      id: '/api/public/bookings'
      path: '/api/public/bookings'
      fullPath: '/api/public/bookings'
      preLoaderRoute: typeof ApiPublicBookingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/leads': {
      id: '/api/public/leads'
      path: '/api/public/leads'
      fullPath: '/api/public/leads'
      preLoaderRoute: typeof ApiPublicLeadsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/offer-checkout': {
      id: '/api/public/offer-checkout'
      path: '/api/public/offer-checkout'
      fullPath: '/api/public/offer-checkout'
      preLoaderRoute: typeof ApiPublicOfferCheckoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/offer-checkout/confirm': {
      id: '/api/public/offer-checkout/confirm'
      path: '/confirm'
      fullPath: '/api/public/offer-checkout/confirm'
      preLoaderRoute: typeof ApiPublicOfferCheckoutConfirmRouteImport
      parentRoute: typeof ApiPublicOfferCheckoutRoute
    }
    '/lovable/email/auth/preview': {
      id: '/lovable/email/auth/preview'
      path: '/lovable/email/auth/preview'
      fullPath: '/lovable/email/auth/preview'
      preLoaderRoute: typeof LovableEmailAuthPreviewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lovable/email/auth/webhook': {
      id: '/lovable/email/auth/webhook'
      path: '/lovable/email/auth/webhook'
      fullPath: '/lovable/email/auth/webhook'
      preLoaderRoute: typeof LovableEmailAuthWebhookRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lovable/email/transactional/preview': {
      id: '/lovable/email/transactional/preview'
      path: '/lovable/email/transactional/preview'
      fullPath: '/lovable/email/transactional/preview'
      preLoaderRoute: typeof LovableEmailTransactionalPreviewRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface ExpertsRouteChildren {
  ExpertsIndexRoute: typeof ExpertsIndexRoute
}

const ExpertsRouteChildren: ExpertsRouteChildren = {
  ExpertsIndexRoute: ExpertsIndexRoute,
}

const ExpertsRouteWithChildren =
  ExpertsRoute._addFileChildren(ExpertsRouteChildren)

interface ThailandCallRouteChildren {
  ThailandCallConfirmedRoute: typeof ThailandCallConfirmedRoute
  ThailandCallIndexRoute: typeof ThailandCallIndexRoute
}

const ThailandCallRouteChildren: ThailandCallRouteChildren = {
  ThailandCallConfirmedRoute: ThailandCallConfirmedRoute,
  ThailandCallIndexRoute: ThailandCallIndexRoute,
}

const ThailandCallRouteWithChildren = ThailandCallRoute._addFileChildren(
  ThailandCallRouteChildren,
)

interface ApiPublicOfferCheckoutRouteChildren {
  ApiPublicOfferCheckoutConfirmRoute: typeof ApiPublicOfferCheckoutConfirmRoute
}

const ApiPublicOfferCheckoutRouteChildren: ApiPublicOfferCheckoutRouteChildren =
  {
    ApiPublicOfferCheckoutConfirmRoute: ApiPublicOfferCheckoutConfirmRoute,
  }

const ApiPublicOfferCheckoutRouteWithChildren =
  ApiPublicOfferCheckoutRoute._addFileChildren(
    ApiPublicOfferCheckoutRouteChildren,
  )

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AssessmentRoute: AssessmentRoute,
  ExpertsRoute: ExpertsRouteWithChildren,
  ResultsRoute: ResultsRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  ThailandCallRoute: ThailandCallRouteWithChildren,
  ApiPublicBookingsRoute: ApiPublicBookingsRoute,
  ApiPublicLeadsRoute: ApiPublicLeadsRoute,
  ApiPublicOfferCheckoutRoute: ApiPublicOfferCheckoutRouteWithChildren,
  LovableEmailAuthPreviewRoute: LovableEmailAuthPreviewRoute,
  LovableEmailAuthWebhookRoute: LovableEmailAuthWebhookRoute,
  LovableEmailTransactionalPreviewRoute: LovableEmailTransactionalPreviewRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
